const UNAUTHORIZED = "UNUNAUTHORIZED";
const FORBIDDEN = "FORBIDDEN";
const EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";

const INVALID_REQUEST = "INVALID_REQUEST";
const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";

const CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND";
const CONTEST_NOT_ACTIVE = "CONTEST_NOT_ACTIVE";

const ALREADY_SUBMITTED = "ALREADY_SUBMITTED";
const QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND";

const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";

export {
  UNAUTHORIZED,
  FORBIDDEN,
  INVALID_REQUEST,
  EMAIL_ALREADY_EXISTS,
  INVALID_CREDENTIALS,
  CONTEST_NOT_FOUND,
  CONTEST_NOT_ACTIVE,
  ALREADY_SUBMITTED,
  QUESTION_NOT_FOUND,
  INTERNAL_SERVER_ERROR,
};
